// Generated by rstantools.  Do not edit by hand.

/*
    raschdash is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    raschdash is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with raschdash.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_raschdash_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_raschdash");
    reader.add_event(180, 178, "end", "model_raschdash");
    return reader;
}
template <bool propto, typename T1__>
typename boost::math::tools::promote_args<T1__>::type
pcm_lpmf(const int& y,
             const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& beta_raw, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 4;
        int K(0);
        (void) K;  // dummy to suppress unused var warning
        stan::math::fill(K, std::numeric_limits<int>::min());
        stan::math::assign(K,num_elements(beta_raw));
        current_statement_begin__ = 5;
        validate_non_negative_index("beta", "(K + 1)", (K + 1));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta((K + 1));
        stan::math::initialize(beta, DUMMY_VAR__);
        stan::math::fill(beta, DUMMY_VAR__);
        stan::math::assign(beta,append_row(0, cumulative_sum(beta_raw)));
        current_statement_begin__ = 6;
        return stan::math::promote_scalar<fun_return_scalar_t__>(categorical_logit_log((y + 1), beta));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
template <typename T1__>
typename boost::math::tools::promote_args<T1__>::type
pcm_lpmf(const int& y,
             const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& beta_raw, std::ostream* pstream__) {
    return pcm_lpmf<false>(y,beta_raw, pstream__);
}
struct pcm_lpmf_functor__ {
    template <bool propto, typename T1__>
        typename boost::math::tools::promote_args<T1__>::type
    operator()(const int& y,
             const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& beta_raw, std::ostream* pstream__) const {
        return pcm_lpmf(y, beta_raw, pstream__);
    }
};
template <typename T0__, class RNG>
int
pcm_rng(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& beta_raw, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef int fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 19;
        int K(0);
        (void) K;  // dummy to suppress unused var warning
        stan::math::fill(K, std::numeric_limits<int>::min());
        stan::math::assign(K,num_elements(beta_raw));
        current_statement_begin__ = 20;
        validate_non_negative_index("beta", "(K + 1)", (K + 1));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta((K + 1));
        stan::math::initialize(beta, DUMMY_VAR__);
        stan::math::fill(beta, DUMMY_VAR__);
        stan::math::assign(beta,append_row(0, cumulative_sum(beta_raw)));
        current_statement_begin__ = 21;
        return stan::math::promote_scalar<fun_return_scalar_t__>((categorical_logit_rng(beta, base_rng__) - 1));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct pcm_rng_functor__ {
    template <typename T0__, class RNG>
        int
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& beta_raw, RNG& base_rng__, std::ostream* pstream__) const {
        return pcm_rng(beta_raw, base_rng__, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_raschdash
  : public stan::model::model_base_crtp<model_raschdash> {
private:
        int L;
        int I;
        int K;
        int M;
        int N;
        int O;
        std::vector<int> mm;
        std::vector<int> nn;
        std::vector<int> ll;
        std::vector<int> ii;
        std::vector<int> kk;
        std::vector<int> y;
        vector_d w;
        int max_item_score;
public:
    model_raschdash(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_raschdash(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_raschdash_namespace::model_raschdash";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 26;
            context__.validate_dims("data initialization", "L", "int", context__.to_vec());
            L = int(0);
            vals_i__ = context__.vals_i("L");
            pos__ = 0;
            L = vals_i__[pos__++];
            check_greater_or_equal(function__, "L", L, 1);
            current_statement_begin__ = 27;
            context__.validate_dims("data initialization", "I", "int", context__.to_vec());
            I = int(0);
            vals_i__ = context__.vals_i("I");
            pos__ = 0;
            I = vals_i__[pos__++];
            check_greater_or_equal(function__, "I", I, 1);
            current_statement_begin__ = 29;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            check_greater_or_equal(function__, "K", K, 1);
            current_statement_begin__ = 30;
            context__.validate_dims("data initialization", "M", "int", context__.to_vec());
            M = int(0);
            vals_i__ = context__.vals_i("M");
            pos__ = 0;
            M = vals_i__[pos__++];
            check_greater_or_equal(function__, "M", M, 1);
            current_statement_begin__ = 31;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 1);
            current_statement_begin__ = 32;
            context__.validate_dims("data initialization", "O", "int", context__.to_vec());
            O = int(0);
            vals_i__ = context__.vals_i("O");
            pos__ = 0;
            O = vals_i__[pos__++];
            check_greater_or_equal(function__, "O", O, 1);
            current_statement_begin__ = 33;
            validate_non_negative_index("mm", "N", N);
            context__.validate_dims("data initialization", "mm", "int", context__.to_vec(N));
            mm = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("mm");
            pos__ = 0;
            size_t mm_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < mm_k_0_max__; ++k_0__) {
                mm[k_0__] = vals_i__[pos__++];
            }
            size_t mm_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < mm_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "mm[i_0__]", mm[i_0__], 1);
                check_less_or_equal(function__, "mm[i_0__]", mm[i_0__], M);
            }
            current_statement_begin__ = 34;
            validate_non_negative_index("nn", "O", O);
            context__.validate_dims("data initialization", "nn", "int", context__.to_vec(O));
            nn = std::vector<int>(O, int(0));
            vals_i__ = context__.vals_i("nn");
            pos__ = 0;
            size_t nn_k_0_max__ = O;
            for (size_t k_0__ = 0; k_0__ < nn_k_0_max__; ++k_0__) {
                nn[k_0__] = vals_i__[pos__++];
            }
            size_t nn_i_0_max__ = O;
            for (size_t i_0__ = 0; i_0__ < nn_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "nn[i_0__]", nn[i_0__], -(M));
                check_less_or_equal(function__, "nn[i_0__]", nn[i_0__], N);
            }
            current_statement_begin__ = 36;
            validate_non_negative_index("ll", "I", I);
            context__.validate_dims("data initialization", "ll", "int", context__.to_vec(I));
            ll = std::vector<int>(I, int(0));
            vals_i__ = context__.vals_i("ll");
            pos__ = 0;
            size_t ll_k_0_max__ = I;
            for (size_t k_0__ = 0; k_0__ < ll_k_0_max__; ++k_0__) {
                ll[k_0__] = vals_i__[pos__++];
            }
            size_t ll_i_0_max__ = I;
            for (size_t i_0__ = 0; i_0__ < ll_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "ll[i_0__]", ll[i_0__], 1);
                check_less_or_equal(function__, "ll[i_0__]", ll[i_0__], L);
            }
            current_statement_begin__ = 37;
            validate_non_negative_index("ii", "O", O);
            context__.validate_dims("data initialization", "ii", "int", context__.to_vec(O));
            ii = std::vector<int>(O, int(0));
            vals_i__ = context__.vals_i("ii");
            pos__ = 0;
            size_t ii_k_0_max__ = O;
            for (size_t k_0__ = 0; k_0__ < ii_k_0_max__; ++k_0__) {
                ii[k_0__] = vals_i__[pos__++];
            }
            size_t ii_i_0_max__ = O;
            for (size_t i_0__ = 0; i_0__ < ii_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "ii[i_0__]", ii[i_0__], 1);
                check_less_or_equal(function__, "ii[i_0__]", ii[i_0__], I);
            }
            current_statement_begin__ = 38;
            validate_non_negative_index("kk", "I", I);
            context__.validate_dims("data initialization", "kk", "int", context__.to_vec(I));
            kk = std::vector<int>(I, int(0));
            vals_i__ = context__.vals_i("kk");
            pos__ = 0;
            size_t kk_k_0_max__ = I;
            for (size_t k_0__ = 0; k_0__ < kk_k_0_max__; ++k_0__) {
                kk[k_0__] = vals_i__[pos__++];
            }
            size_t kk_i_0_max__ = I;
            for (size_t i_0__ = 0; i_0__ < kk_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "kk[i_0__]", kk[i_0__], 1);
            }
            current_statement_begin__ = 43;
            validate_non_negative_index("y", "O", O);
            context__.validate_dims("data initialization", "y", "int", context__.to_vec(O));
            y = std::vector<int>(O, int(0));
            vals_i__ = context__.vals_i("y");
            pos__ = 0;
            size_t y_k_0_max__ = O;
            for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                y[k_0__] = vals_i__[pos__++];
            }
            size_t y_i_0_max__ = O;
            for (size_t i_0__ = 0; i_0__ < y_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "y[i_0__]", y[i_0__], 0);
            }
            current_statement_begin__ = 44;
            validate_non_negative_index("w", "O", O);
            context__.validate_dims("data initialization", "w", "vector_d", context__.to_vec(O));
            w = Eigen::Matrix<double, Eigen::Dynamic, 1>(O);
            vals_r__ = context__.vals_r("w");
            pos__ = 0;
            size_t w_j_1_max__ = O;
            for (size_t j_1__ = 0; j_1__ < w_j_1_max__; ++j_1__) {
                w(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "w", w, 0);
            // initialize transformed data variables
            current_statement_begin__ = 48;
            max_item_score = int(0);
            stan::math::fill(max_item_score, std::numeric_limits<int>::min());
            stan::math::assign(max_item_score,max(kk));
            // execute transformed data statements
            // validate transformed data
            current_statement_begin__ = 48;
            check_greater_or_equal(function__, "max_item_score", max_item_score, 1);
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 54;
            num_params_r__ += 1;
            current_statement_begin__ = 55;
            validate_non_negative_index("epsilon_raw", "(logical_gt(L, 1) ? L : 0 )", (logical_gt(L, 1) ? L : 0 ));
            num_params_r__ += (logical_gt(L, 1) ? L : 0 );
            current_statement_begin__ = 56;
            validate_non_negative_index("upsilon_raw", "I", I);
            num_params_r__ += I;
            current_statement_begin__ = 57;
            validate_non_negative_index("tau_raw", "(logical_gt(K, 1) ? K : 0 )", (logical_gt(K, 1) ? K : 0 ));
            num_params_r__ += (logical_gt(K, 1) ? K : 0 );
            current_statement_begin__ = 58;
            validate_non_negative_index("xi_raw", "(logical_gt(M, 1) ? M : 0 )", (logical_gt(M, 1) ? M : 0 ));
            num_params_r__ += (logical_gt(M, 1) ? M : 0 );
            current_statement_begin__ = 59;
            validate_non_negative_index("zeta_raw", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 60;
            validate_non_negative_index("theta_epsilon", "(logical_gt(L, 1) ? 1 : 0 )", (logical_gt(L, 1) ? 1 : 0 ));
            num_params_r__ += (logical_gt(L, 1) ? 1 : 0 );
            current_statement_begin__ = 62;
            num_params_r__ += 1;
            current_statement_begin__ = 63;
            validate_non_negative_index("theta_tau", "(logical_gt(K, 1) ? 1 : 0 )", (logical_gt(K, 1) ? 1 : 0 ));
            num_params_r__ += (logical_gt(K, 1) ? 1 : 0 );
            current_statement_begin__ = 65;
            validate_non_negative_index("psi", "(logical_gt(M, 1) ? 1 : 0 )", (logical_gt(M, 1) ? 1 : 0 ));
            num_params_r__ += (logical_gt(M, 1) ? 1 : 0 );
            current_statement_begin__ = 66;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_raschdash() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 54;
        if (!(context__.contains_r("nu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable nu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("nu");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "nu", "double", context__.to_vec());
        double nu(0);
        nu = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(nu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable nu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 55;
        if (!(context__.contains_r("epsilon_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable epsilon_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("epsilon_raw");
        pos__ = 0U;
        validate_non_negative_index("epsilon_raw", "(logical_gt(L, 1) ? L : 0 )", (logical_gt(L, 1) ? L : 0 ));
        context__.validate_dims("parameter initialization", "epsilon_raw", "vector_d", context__.to_vec((logical_gt(L, 1) ? L : 0 )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> epsilon_raw((logical_gt(L, 1) ? L : 0 ));
        size_t epsilon_raw_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
        for (size_t j_1__ = 0; j_1__ < epsilon_raw_j_1_max__; ++j_1__) {
            epsilon_raw(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(epsilon_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable epsilon_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 56;
        if (!(context__.contains_r("upsilon_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable upsilon_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("upsilon_raw");
        pos__ = 0U;
        validate_non_negative_index("upsilon_raw", "I", I);
        context__.validate_dims("parameter initialization", "upsilon_raw", "vector_d", context__.to_vec(I));
        Eigen::Matrix<double, Eigen::Dynamic, 1> upsilon_raw(I);
        size_t upsilon_raw_j_1_max__ = I;
        for (size_t j_1__ = 0; j_1__ < upsilon_raw_j_1_max__; ++j_1__) {
            upsilon_raw(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(upsilon_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable upsilon_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 57;
        if (!(context__.contains_r("tau_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable tau_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("tau_raw");
        pos__ = 0U;
        validate_non_negative_index("tau_raw", "(logical_gt(K, 1) ? K : 0 )", (logical_gt(K, 1) ? K : 0 ));
        context__.validate_dims("parameter initialization", "tau_raw", "vector_d", context__.to_vec((logical_gt(K, 1) ? K : 0 )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> tau_raw((logical_gt(K, 1) ? K : 0 ));
        size_t tau_raw_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
        for (size_t j_1__ = 0; j_1__ < tau_raw_j_1_max__; ++j_1__) {
            tau_raw(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(tau_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable tau_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 58;
        if (!(context__.contains_r("xi_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable xi_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("xi_raw");
        pos__ = 0U;
        validate_non_negative_index("xi_raw", "(logical_gt(M, 1) ? M : 0 )", (logical_gt(M, 1) ? M : 0 ));
        context__.validate_dims("parameter initialization", "xi_raw", "vector_d", context__.to_vec((logical_gt(M, 1) ? M : 0 )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> xi_raw((logical_gt(M, 1) ? M : 0 ));
        size_t xi_raw_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
        for (size_t j_1__ = 0; j_1__ < xi_raw_j_1_max__; ++j_1__) {
            xi_raw(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(xi_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable xi_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 59;
        if (!(context__.contains_r("zeta_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable zeta_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("zeta_raw");
        pos__ = 0U;
        validate_non_negative_index("zeta_raw", "N", N);
        context__.validate_dims("parameter initialization", "zeta_raw", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> zeta_raw(N);
        size_t zeta_raw_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < zeta_raw_j_1_max__; ++j_1__) {
            zeta_raw(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(zeta_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable zeta_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 60;
        if (!(context__.contains_r("theta_epsilon")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_epsilon missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_epsilon");
        pos__ = 0U;
        validate_non_negative_index("theta_epsilon", "(logical_gt(L, 1) ? 1 : 0 )", (logical_gt(L, 1) ? 1 : 0 ));
        context__.validate_dims("parameter initialization", "theta_epsilon", "vector_d", context__.to_vec((logical_gt(L, 1) ? 1 : 0 )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_epsilon((logical_gt(L, 1) ? 1 : 0 ));
        size_t theta_epsilon_j_1_max__ = (logical_gt(L, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < theta_epsilon_j_1_max__; ++j_1__) {
            theta_epsilon(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, theta_epsilon);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_epsilon: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 62;
        if (!(context__.contains_r("theta_upsilon_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_upsilon_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_upsilon_raw");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "theta_upsilon_raw", "double", context__.to_vec());
        double theta_upsilon_raw(0);
        theta_upsilon_raw = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, theta_upsilon_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_upsilon_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 63;
        if (!(context__.contains_r("theta_tau")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_tau missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_tau");
        pos__ = 0U;
        validate_non_negative_index("theta_tau", "(logical_gt(K, 1) ? 1 : 0 )", (logical_gt(K, 1) ? 1 : 0 ));
        context__.validate_dims("parameter initialization", "theta_tau", "vector_d", context__.to_vec((logical_gt(K, 1) ? 1 : 0 )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_tau((logical_gt(K, 1) ? 1 : 0 ));
        size_t theta_tau_j_1_max__ = (logical_gt(K, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < theta_tau_j_1_max__; ++j_1__) {
            theta_tau(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, theta_tau);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_tau: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 65;
        if (!(context__.contains_r("psi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable psi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("psi");
        pos__ = 0U;
        validate_non_negative_index("psi", "(logical_gt(M, 1) ? 1 : 0 )", (logical_gt(M, 1) ? 1 : 0 ));
        context__.validate_dims("parameter initialization", "psi", "vector_d", context__.to_vec((logical_gt(M, 1) ? 1 : 0 )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> psi((logical_gt(M, 1) ? 1 : 0 ));
        size_t psi_j_1_max__ = (logical_gt(M, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < psi_j_1_max__; ++j_1__) {
            psi(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, psi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable psi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 66;
        if (!(context__.contains_r("phi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable phi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "phi", "double", context__.to_vec());
        double phi(0);
        phi = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, phi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable phi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 54;
            local_scalar_t__ nu;
            (void) nu;  // dummy to suppress unused var warning
            if (jacobian__)
                nu = in__.scalar_constrain(lp__);
            else
                nu = in__.scalar_constrain();
            current_statement_begin__ = 55;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> epsilon_raw;
            (void) epsilon_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                epsilon_raw = in__.vector_constrain((logical_gt(L, 1) ? L : 0 ), lp__);
            else
                epsilon_raw = in__.vector_constrain((logical_gt(L, 1) ? L : 0 ));
            current_statement_begin__ = 56;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> upsilon_raw;
            (void) upsilon_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                upsilon_raw = in__.vector_constrain(I, lp__);
            else
                upsilon_raw = in__.vector_constrain(I);
            current_statement_begin__ = 57;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> tau_raw;
            (void) tau_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                tau_raw = in__.vector_constrain((logical_gt(K, 1) ? K : 0 ), lp__);
            else
                tau_raw = in__.vector_constrain((logical_gt(K, 1) ? K : 0 ));
            current_statement_begin__ = 58;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> xi_raw;
            (void) xi_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                xi_raw = in__.vector_constrain((logical_gt(M, 1) ? M : 0 ), lp__);
            else
                xi_raw = in__.vector_constrain((logical_gt(M, 1) ? M : 0 ));
            current_statement_begin__ = 59;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> zeta_raw;
            (void) zeta_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                zeta_raw = in__.vector_constrain(N, lp__);
            else
                zeta_raw = in__.vector_constrain(N);
            current_statement_begin__ = 60;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> theta_epsilon;
            (void) theta_epsilon;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_epsilon = in__.vector_lb_constrain(0, (logical_gt(L, 1) ? 1 : 0 ), lp__);
            else
                theta_epsilon = in__.vector_lb_constrain(0, (logical_gt(L, 1) ? 1 : 0 ));
            current_statement_begin__ = 62;
            local_scalar_t__ theta_upsilon_raw;
            (void) theta_upsilon_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_upsilon_raw = in__.scalar_lb_constrain(0, lp__);
            else
                theta_upsilon_raw = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 63;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> theta_tau;
            (void) theta_tau;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_tau = in__.vector_lb_constrain(0, (logical_gt(K, 1) ? 1 : 0 ), lp__);
            else
                theta_tau = in__.vector_lb_constrain(0, (logical_gt(K, 1) ? 1 : 0 ));
            current_statement_begin__ = 65;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> psi;
            (void) psi;  // dummy to suppress unused var warning
            if (jacobian__)
                psi = in__.vector_lb_constrain(0, (logical_gt(M, 1) ? 1 : 0 ), lp__);
            else
                psi = in__.vector_lb_constrain(0, (logical_gt(M, 1) ? 1 : 0 ));
            current_statement_begin__ = 66;
            local_scalar_t__ phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.scalar_lb_constrain(0, lp__);
            else
                phi = in__.scalar_lb_constrain(0);
            // transformed parameters
            current_statement_begin__ = 70;
            local_scalar_t__ theta_upsilon;
            (void) theta_upsilon;  // dummy to suppress unused var warning
            stan::math::initialize(theta_upsilon, DUMMY_VAR__);
            stan::math::fill(theta_upsilon, DUMMY_VAR__);
            stan::math::assign(theta_upsilon,(logical_gt(K, 1) ? stan::math::promote_scalar<local_scalar_t__>(stan::math::sqrt((square(theta_upsilon_raw) + square(get_base1(theta_tau, 1, "theta_tau", 1))))) : stan::math::promote_scalar<local_scalar_t__>(theta_upsilon_raw) ));
            current_statement_begin__ = 74;
            validate_non_negative_index("epsilon", "(logical_gt(L, 1) ? L : 0 )", (logical_gt(L, 1) ? L : 0 ));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> epsilon((logical_gt(L, 1) ? L : 0 ));
            stan::math::initialize(epsilon, DUMMY_VAR__);
            stan::math::fill(epsilon, DUMMY_VAR__);
            current_statement_begin__ = 75;
            validate_non_negative_index("delta", "I", I);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> delta(I);
            stan::math::initialize(delta, DUMMY_VAR__);
            stan::math::fill(delta, DUMMY_VAR__);
            current_statement_begin__ = 76;
            validate_non_negative_index("tau", "(logical_gt(K, 1) ? K : 0 )", (logical_gt(K, 1) ? K : 0 ));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> tau((logical_gt(K, 1) ? K : 0 ));
            stan::math::initialize(tau, DUMMY_VAR__);
            stan::math::fill(tau, DUMMY_VAR__);
            current_statement_begin__ = 77;
            validate_non_negative_index("xi", "(logical_gt(M, 1) ? M : 0 )", (logical_gt(M, 1) ? M : 0 ));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> xi((logical_gt(M, 1) ? M : 0 ));
            stan::math::initialize(xi, DUMMY_VAR__);
            stan::math::fill(xi, DUMMY_VAR__);
            current_statement_begin__ = 78;
            validate_non_negative_index("eta", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> eta(N);
            stan::math::initialize(eta, DUMMY_VAR__);
            stan::math::fill(eta, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 79;
            if (as_bool(logical_gt(L, 1))) {
                current_statement_begin__ = 79;
                stan::math::assign(epsilon, add(nu, multiply(get_base1(theta_epsilon, 1, "theta_epsilon", 1), epsilon_raw)));
            }
            current_statement_begin__ = 80;
            stan::math::assign(delta, (logical_gt(L, 1) ? stan::math::promote_scalar<local_scalar_t__>(stan::model::rvalue(epsilon, stan::model::cons_list(stan::model::index_multi(ll), stan::model::nil_index_list()), "epsilon")) : stan::math::promote_scalar<local_scalar_t__>(rep_vector(nu, I)) ));
            current_statement_begin__ = 82;
            for (int i = 1; i <= I; ++i) {
                current_statement_begin__ = 83;
                stan::math::assign(delta, add(delta, multiply((logical_eq(get_base1(kk, i, "kk", 1), K) ? stan::math::promote_scalar<local_scalar_t__>(theta_upsilon_raw) : stan::math::promote_scalar<local_scalar_t__>(theta_upsilon) ), upsilon_raw)));
            }
            current_statement_begin__ = 85;
            if (as_bool(logical_gt(K, 1))) {
                current_statement_begin__ = 85;
                stan::math::assign(tau, multiply(get_base1(theta_tau, 1, "theta_tau", 1), tau_raw));
            }
            current_statement_begin__ = 86;
            if (as_bool(logical_gt(M, 1))) {
                current_statement_begin__ = 87;
                stan::math::assign(xi, multiply(get_base1(psi, 1, "psi", 1), xi_raw));
                current_statement_begin__ = 88;
                stan::math::assign(eta, add(stan::model::rvalue(xi, stan::model::cons_list(stan::model::index_multi(mm), stan::model::nil_index_list()), "xi"), multiply(phi, zeta_raw)));
            } else {
                current_statement_begin__ = 90;
                stan::math::assign(eta, multiply(phi, zeta_raw));
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 70;
            if (stan::math::is_uninitialized(theta_upsilon)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: theta_upsilon";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable theta_upsilon: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            check_greater_or_equal(function__, "theta_upsilon", theta_upsilon, 0);
            current_statement_begin__ = 74;
            size_t epsilon_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
            for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(epsilon(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: epsilon" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable epsilon: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 75;
            size_t delta_j_1_max__ = I;
            for (size_t j_1__ = 0; j_1__ < delta_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(delta(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: delta" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable delta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 76;
            size_t tau_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
            for (size_t j_1__ = 0; j_1__ < tau_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(tau(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: tau" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable tau: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 77;
            size_t xi_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
            for (size_t j_1__ = 0; j_1__ < xi_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(xi(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: xi" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable xi: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 78;
            size_t eta_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(eta(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: eta" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable eta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            current_statement_begin__ = 100;
            lp_accum__.add(std_normal_log<propto__>(nu));
            current_statement_begin__ = 101;
            lp_accum__.add(std_normal_log<propto__>(epsilon_raw));
            current_statement_begin__ = 102;
            lp_accum__.add(std_normal_log<propto__>(upsilon_raw));
            current_statement_begin__ = 103;
            lp_accum__.add(std_normal_log<propto__>(tau_raw));
            current_statement_begin__ = 104;
            lp_accum__.add(std_normal_log<propto__>(xi_raw));
            current_statement_begin__ = 105;
            lp_accum__.add(std_normal_log<propto__>(zeta_raw));
            current_statement_begin__ = 106;
            lp_accum__.add(std_normal_log<propto__>(theta_epsilon));
            current_statement_begin__ = 107;
            lp_accum__.add(std_normal_log<propto__>(theta_upsilon_raw));
            current_statement_begin__ = 108;
            lp_accum__.add(std_normal_log<propto__>(theta_tau));
            current_statement_begin__ = 109;
            lp_accum__.add(std_normal_log<propto__>(psi));
            current_statement_begin__ = 110;
            lp_accum__.add(std_normal_log<propto__>(phi));
            current_statement_begin__ = 111;
            for (int o = 1; o <= O; ++o) {
                {
                current_statement_begin__ = 112;
                int i(0);
                (void) i;  // dummy to suppress unused var warning
                stan::math::fill(i, std::numeric_limits<int>::min());
                stan::math::assign(i,get_base1(ii, o, "ii", 1));
                current_statement_begin__ = 113;
                int k(0);
                (void) k;  // dummy to suppress unused var warning
                stan::math::fill(k, std::numeric_limits<int>::min());
                stan::math::assign(k,get_base1(kk, i, "kk", 1));
                current_statement_begin__ = 114;
                int n(0);
                (void) n;  // dummy to suppress unused var warning
                stan::math::fill(n, std::numeric_limits<int>::min());
                stan::math::assign(n,get_base1(nn, o, "nn", 1));
                current_statement_begin__ = 115;
                local_scalar_t__ beta(DUMMY_VAR__);
                (void) beta;  // dummy to suppress unused var warning
                stan::math::initialize(beta, DUMMY_VAR__);
                stan::math::fill(beta, DUMMY_VAR__);
                stan::math::assign(beta,((logical_lt(n, 0) ? stan::math::promote_scalar<local_scalar_t__>(get_base1(xi, -(n), "xi", 1)) : stan::math::promote_scalar<local_scalar_t__>(get_base1(eta, n, "eta", 1)) ) - get_base1(delta, i, "delta", 1)));
                current_statement_begin__ = 119;
                if (as_bool(logical_eq(k, 1))) {
                    current_statement_begin__ = 119;
                    lp_accum__.add((get_base1(w, o, "w", 1) * bernoulli_logit_log(get_base1(y, o, "y", 1), beta)));
                } else if (as_bool(logical_eq(k, K))) {
                    current_statement_begin__ = 120;
                    lp_accum__.add((get_base1(w, o, "w", 1) * pcm_lpmf(get_base1(y, o, "y", 1), subtract(beta, tau), pstream__)));
                } else {
                    current_statement_begin__ = 121;
                    lp_accum__.add((get_base1(w, o, "w", 1) * binomial_logit_log(get_base1(y, o, "y", 1), k, beta)));
                }
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("nu");
        names__.push_back("epsilon_raw");
        names__.push_back("upsilon_raw");
        names__.push_back("tau_raw");
        names__.push_back("xi_raw");
        names__.push_back("zeta_raw");
        names__.push_back("theta_epsilon");
        names__.push_back("theta_upsilon_raw");
        names__.push_back("theta_tau");
        names__.push_back("psi");
        names__.push_back("phi");
        names__.push_back("theta_upsilon");
        names__.push_back("epsilon");
        names__.push_back("delta");
        names__.push_back("tau");
        names__.push_back("xi");
        names__.push_back("eta");
        names__.push_back("sigma");
        names__.push_back("testlet_difficulty");
        names__.push_back("item_difficulty");
        names__.push_back("thresholds");
        names__.push_back("group_ability");
        names__.push_back("person_ability");
        names__.push_back("y_rep");
        names__.push_back("log_lik");
        names__.push_back("log_lik_rep");
        names__.push_back("log_lik_prior_person");
        names__.push_back("log_lik_prior_item");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(L, 1) ? L : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(I);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(K, 1) ? K : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(M, 1) ? M : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(L, 1) ? 1 : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(K, 1) ? 1 : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(M, 1) ? 1 : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(L, 1) ? L : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(I);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(K, 1) ? K : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(M, 1) ? M : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(L, 1) ? L : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(I);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(K, 1) ? K : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_gt(M, 1) ? M : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(O);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(O);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(O);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(O);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(O);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_raschdash_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double nu = in__.scalar_constrain();
        vars__.push_back(nu);
        Eigen::Matrix<double, Eigen::Dynamic, 1> epsilon_raw = in__.vector_constrain((logical_gt(L, 1) ? L : 0 ));
        size_t epsilon_raw_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
        for (size_t j_1__ = 0; j_1__ < epsilon_raw_j_1_max__; ++j_1__) {
            vars__.push_back(epsilon_raw(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> upsilon_raw = in__.vector_constrain(I);
        size_t upsilon_raw_j_1_max__ = I;
        for (size_t j_1__ = 0; j_1__ < upsilon_raw_j_1_max__; ++j_1__) {
            vars__.push_back(upsilon_raw(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> tau_raw = in__.vector_constrain((logical_gt(K, 1) ? K : 0 ));
        size_t tau_raw_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
        for (size_t j_1__ = 0; j_1__ < tau_raw_j_1_max__; ++j_1__) {
            vars__.push_back(tau_raw(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> xi_raw = in__.vector_constrain((logical_gt(M, 1) ? M : 0 ));
        size_t xi_raw_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
        for (size_t j_1__ = 0; j_1__ < xi_raw_j_1_max__; ++j_1__) {
            vars__.push_back(xi_raw(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> zeta_raw = in__.vector_constrain(N);
        size_t zeta_raw_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < zeta_raw_j_1_max__; ++j_1__) {
            vars__.push_back(zeta_raw(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_epsilon = in__.vector_lb_constrain(0, (logical_gt(L, 1) ? 1 : 0 ));
        size_t theta_epsilon_j_1_max__ = (logical_gt(L, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < theta_epsilon_j_1_max__; ++j_1__) {
            vars__.push_back(theta_epsilon(j_1__));
        }
        double theta_upsilon_raw = in__.scalar_lb_constrain(0);
        vars__.push_back(theta_upsilon_raw);
        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_tau = in__.vector_lb_constrain(0, (logical_gt(K, 1) ? 1 : 0 ));
        size_t theta_tau_j_1_max__ = (logical_gt(K, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < theta_tau_j_1_max__; ++j_1__) {
            vars__.push_back(theta_tau(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> psi = in__.vector_lb_constrain(0, (logical_gt(M, 1) ? 1 : 0 ));
        size_t psi_j_1_max__ = (logical_gt(M, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < psi_j_1_max__; ++j_1__) {
            vars__.push_back(psi(j_1__));
        }
        double phi = in__.scalar_lb_constrain(0);
        vars__.push_back(phi);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 70;
            double theta_upsilon;
            (void) theta_upsilon;  // dummy to suppress unused var warning
            stan::math::initialize(theta_upsilon, DUMMY_VAR__);
            stan::math::fill(theta_upsilon, DUMMY_VAR__);
            stan::math::assign(theta_upsilon,(logical_gt(K, 1) ? stan::math::promote_scalar<local_scalar_t__>(stan::math::sqrt((square(theta_upsilon_raw) + square(get_base1(theta_tau, 1, "theta_tau", 1))))) : stan::math::promote_scalar<local_scalar_t__>(theta_upsilon_raw) ));
            current_statement_begin__ = 74;
            validate_non_negative_index("epsilon", "(logical_gt(L, 1) ? L : 0 )", (logical_gt(L, 1) ? L : 0 ));
            Eigen::Matrix<double, Eigen::Dynamic, 1> epsilon((logical_gt(L, 1) ? L : 0 ));
            stan::math::initialize(epsilon, DUMMY_VAR__);
            stan::math::fill(epsilon, DUMMY_VAR__);
            current_statement_begin__ = 75;
            validate_non_negative_index("delta", "I", I);
            Eigen::Matrix<double, Eigen::Dynamic, 1> delta(I);
            stan::math::initialize(delta, DUMMY_VAR__);
            stan::math::fill(delta, DUMMY_VAR__);
            current_statement_begin__ = 76;
            validate_non_negative_index("tau", "(logical_gt(K, 1) ? K : 0 )", (logical_gt(K, 1) ? K : 0 ));
            Eigen::Matrix<double, Eigen::Dynamic, 1> tau((logical_gt(K, 1) ? K : 0 ));
            stan::math::initialize(tau, DUMMY_VAR__);
            stan::math::fill(tau, DUMMY_VAR__);
            current_statement_begin__ = 77;
            validate_non_negative_index("xi", "(logical_gt(M, 1) ? M : 0 )", (logical_gt(M, 1) ? M : 0 ));
            Eigen::Matrix<double, Eigen::Dynamic, 1> xi((logical_gt(M, 1) ? M : 0 ));
            stan::math::initialize(xi, DUMMY_VAR__);
            stan::math::fill(xi, DUMMY_VAR__);
            current_statement_begin__ = 78;
            validate_non_negative_index("eta", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> eta(N);
            stan::math::initialize(eta, DUMMY_VAR__);
            stan::math::fill(eta, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 79;
            if (as_bool(logical_gt(L, 1))) {
                current_statement_begin__ = 79;
                stan::math::assign(epsilon, add(nu, multiply(get_base1(theta_epsilon, 1, "theta_epsilon", 1), epsilon_raw)));
            }
            current_statement_begin__ = 80;
            stan::math::assign(delta, (logical_gt(L, 1) ? stan::math::promote_scalar<local_scalar_t__>(stan::model::rvalue(epsilon, stan::model::cons_list(stan::model::index_multi(ll), stan::model::nil_index_list()), "epsilon")) : stan::math::promote_scalar<local_scalar_t__>(rep_vector(nu, I)) ));
            current_statement_begin__ = 82;
            for (int i = 1; i <= I; ++i) {
                current_statement_begin__ = 83;
                stan::math::assign(delta, add(delta, multiply((logical_eq(get_base1(kk, i, "kk", 1), K) ? stan::math::promote_scalar<local_scalar_t__>(theta_upsilon_raw) : stan::math::promote_scalar<local_scalar_t__>(theta_upsilon) ), upsilon_raw)));
            }
            current_statement_begin__ = 85;
            if (as_bool(logical_gt(K, 1))) {
                current_statement_begin__ = 85;
                stan::math::assign(tau, multiply(get_base1(theta_tau, 1, "theta_tau", 1), tau_raw));
            }
            current_statement_begin__ = 86;
            if (as_bool(logical_gt(M, 1))) {
                current_statement_begin__ = 87;
                stan::math::assign(xi, multiply(get_base1(psi, 1, "psi", 1), xi_raw));
                current_statement_begin__ = 88;
                stan::math::assign(eta, add(stan::model::rvalue(xi, stan::model::cons_list(stan::model::index_multi(mm), stan::model::nil_index_list()), "xi"), multiply(phi, zeta_raw)));
            } else {
                current_statement_begin__ = 90;
                stan::math::assign(eta, multiply(phi, zeta_raw));
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 70;
            check_greater_or_equal(function__, "theta_upsilon", theta_upsilon, 0);
            // write transformed parameters
            if (include_tparams__) {
                vars__.push_back(theta_upsilon);
                size_t epsilon_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
                for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
                    vars__.push_back(epsilon(j_1__));
                }
                size_t delta_j_1_max__ = I;
                for (size_t j_1__ = 0; j_1__ < delta_j_1_max__; ++j_1__) {
                    vars__.push_back(delta(j_1__));
                }
                size_t tau_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
                for (size_t j_1__ = 0; j_1__ < tau_j_1_max__; ++j_1__) {
                    vars__.push_back(tau(j_1__));
                }
                size_t xi_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
                for (size_t j_1__ = 0; j_1__ < xi_j_1_max__; ++j_1__) {
                    vars__.push_back(xi(j_1__));
                }
                size_t eta_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
                    vars__.push_back(eta(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 126;
            double sigma;
            (void) sigma;  // dummy to suppress unused var warning
            stan::math::initialize(sigma, DUMMY_VAR__);
            stan::math::fill(sigma, DUMMY_VAR__);
            stan::math::assign(sigma,(logical_gt(M, 1) ? stan::math::promote_scalar<local_scalar_t__>(stan::math::sqrt((square(get_base1(psi, 1, "psi", 1)) + square(phi)))) : stan::math::promote_scalar<local_scalar_t__>(phi) ));
            current_statement_begin__ = 128;
            validate_non_negative_index("testlet_difficulty", "(logical_gt(L, 1) ? L : 0 )", (logical_gt(L, 1) ? L : 0 ));
            Eigen::Matrix<double, Eigen::Dynamic, 1> testlet_difficulty((logical_gt(L, 1) ? L : 0 ));
            stan::math::initialize(testlet_difficulty, DUMMY_VAR__);
            stan::math::fill(testlet_difficulty, DUMMY_VAR__);
            stan::math::assign(testlet_difficulty,divide(epsilon, sigma));
            current_statement_begin__ = 129;
            validate_non_negative_index("item_difficulty", "I", I);
            Eigen::Matrix<double, Eigen::Dynamic, 1> item_difficulty(I);
            stan::math::initialize(item_difficulty, DUMMY_VAR__);
            stan::math::fill(item_difficulty, DUMMY_VAR__);
            stan::math::assign(item_difficulty,divide(delta, sigma));
            current_statement_begin__ = 130;
            validate_non_negative_index("thresholds", "(logical_gt(K, 1) ? K : 0 )", (logical_gt(K, 1) ? K : 0 ));
            Eigen::Matrix<double, Eigen::Dynamic, 1> thresholds((logical_gt(K, 1) ? K : 0 ));
            stan::math::initialize(thresholds, DUMMY_VAR__);
            stan::math::fill(thresholds, DUMMY_VAR__);
            stan::math::assign(thresholds,divide(tau, sigma));
            current_statement_begin__ = 131;
            validate_non_negative_index("group_ability", "(logical_gt(M, 1) ? M : 0 )", (logical_gt(M, 1) ? M : 0 ));
            Eigen::Matrix<double, Eigen::Dynamic, 1> group_ability((logical_gt(M, 1) ? M : 0 ));
            stan::math::initialize(group_ability, DUMMY_VAR__);
            stan::math::fill(group_ability, DUMMY_VAR__);
            stan::math::assign(group_ability,divide(xi, sigma));
            current_statement_begin__ = 132;
            validate_non_negative_index("person_ability", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> person_ability(N);
            stan::math::initialize(person_ability, DUMMY_VAR__);
            stan::math::fill(person_ability, DUMMY_VAR__);
            stan::math::assign(person_ability,divide(eta, sigma));
            current_statement_begin__ = 133;
            validate_non_negative_index("y_rep", "O", O);
            std::vector<int> y_rep(O, int(0));
            stan::math::fill(y_rep, std::numeric_limits<int>::min());
            current_statement_begin__ = 134;
            validate_non_negative_index("log_lik", "O", O);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(O);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            current_statement_begin__ = 135;
            validate_non_negative_index("log_lik_rep", "O", O);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik_rep(O);
            stan::math::initialize(log_lik_rep, DUMMY_VAR__);
            stan::math::fill(log_lik_rep, DUMMY_VAR__);
            current_statement_begin__ = 136;
            validate_non_negative_index("log_lik_prior_person", "O", O);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik_prior_person(O);
            stan::math::initialize(log_lik_prior_person, DUMMY_VAR__);
            stan::math::fill(log_lik_prior_person, DUMMY_VAR__);
            current_statement_begin__ = 137;
            validate_non_negative_index("log_lik_prior_item", "O", O);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik_prior_item(O);
            stan::math::initialize(log_lik_prior_item, DUMMY_VAR__);
            stan::math::fill(log_lik_prior_item, DUMMY_VAR__);
            // generated quantities statements
            {
            current_statement_begin__ = 140;
            local_scalar_t__ prior_xi(DUMMY_VAR__);
            (void) prior_xi;  // dummy to suppress unused var warning
            stan::math::initialize(prior_xi, DUMMY_VAR__);
            stan::math::fill(prior_xi, DUMMY_VAR__);
            stan::math::assign(prior_xi,(logical_gt(M, 1) ? stan::math::promote_scalar<local_scalar_t__>(normal_rng(0, get_base1(psi, 1, "psi", 1), base_rng__)) : stan::math::promote_scalar<local_scalar_t__>(0) ));
            current_statement_begin__ = 141;
            local_scalar_t__ prior_eta(DUMMY_VAR__);
            (void) prior_eta;  // dummy to suppress unused var warning
            stan::math::initialize(prior_eta, DUMMY_VAR__);
            stan::math::fill(prior_eta, DUMMY_VAR__);
            stan::math::assign(prior_eta,normal_rng(prior_xi, phi, base_rng__));
            current_statement_begin__ = 142;
            local_scalar_t__ prior_epsilon(DUMMY_VAR__);
            (void) prior_epsilon;  // dummy to suppress unused var warning
            stan::math::initialize(prior_epsilon, DUMMY_VAR__);
            stan::math::fill(prior_epsilon, DUMMY_VAR__);
            stan::math::assign(prior_epsilon,(logical_gt(L, 1) ? stan::math::promote_scalar<local_scalar_t__>(normal_rng(nu, get_base1(theta_epsilon, 1, "theta_epsilon", 1), base_rng__)) : stan::math::promote_scalar<local_scalar_t__>(nu) ));
            current_statement_begin__ = 143;
            local_scalar_t__ prior_delta_raw(DUMMY_VAR__);
            (void) prior_delta_raw;  // dummy to suppress unused var warning
            stan::math::initialize(prior_delta_raw, DUMMY_VAR__);
            stan::math::fill(prior_delta_raw, DUMMY_VAR__);
            stan::math::assign(prior_delta_raw,normal_rng(prior_epsilon, theta_upsilon_raw, base_rng__));
            current_statement_begin__ = 144;
            local_scalar_t__ prior_delta(DUMMY_VAR__);
            (void) prior_delta;  // dummy to suppress unused var warning
            stan::math::initialize(prior_delta, DUMMY_VAR__);
            stan::math::fill(prior_delta, DUMMY_VAR__);
            stan::math::assign(prior_delta,normal_rng(prior_epsilon, theta_upsilon, base_rng__));
            current_statement_begin__ = 145;
            validate_non_negative_index("prior_tau", "K", K);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> prior_tau(K);
            stan::math::initialize(prior_tau, DUMMY_VAR__);
            stan::math::fill(prior_tau, DUMMY_VAR__);
            current_statement_begin__ = 146;
            if (as_bool(logical_gt(K, 1))) {
                current_statement_begin__ = 146;
                for (int k = 1; k <= K; ++k) {
                    current_statement_begin__ = 146;
                    stan::model::assign(prior_tau, 
                                stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                                normal_rng(0, get_base1(theta_tau, 1, "theta_tau", 1), base_rng__), 
                                "assigning variable prior_tau");
                }
            }
            current_statement_begin__ = 147;
            for (int o = 1; o <= O; ++o) {
                {
                current_statement_begin__ = 148;
                int i(0);
                (void) i;  // dummy to suppress unused var warning
                stan::math::fill(i, std::numeric_limits<int>::min());
                stan::math::assign(i,get_base1(ii, o, "ii", 1));
                current_statement_begin__ = 149;
                int k(0);
                (void) k;  // dummy to suppress unused var warning
                stan::math::fill(k, std::numeric_limits<int>::min());
                stan::math::assign(k,get_base1(kk, i, "kk", 1));
                current_statement_begin__ = 150;
                int n(0);
                (void) n;  // dummy to suppress unused var warning
                stan::math::fill(n, std::numeric_limits<int>::min());
                stan::math::assign(n,get_base1(nn, o, "nn", 1));
                current_statement_begin__ = 151;
                local_scalar_t__ beta(DUMMY_VAR__);
                (void) beta;  // dummy to suppress unused var warning
                stan::math::initialize(beta, DUMMY_VAR__);
                stan::math::fill(beta, DUMMY_VAR__);
                stan::math::assign(beta,((logical_lt(n, 0) ? stan::math::promote_scalar<local_scalar_t__>(get_base1(xi, -(n), "xi", 1)) : stan::math::promote_scalar<local_scalar_t__>(get_base1(eta, n, "eta", 1)) ) - get_base1(delta, i, "delta", 1)));
                current_statement_begin__ = 152;
                local_scalar_t__ beta_prior_person(DUMMY_VAR__);
                (void) beta_prior_person;  // dummy to suppress unused var warning
                stan::math::initialize(beta_prior_person, DUMMY_VAR__);
                stan::math::fill(beta_prior_person, DUMMY_VAR__);
                stan::math::assign(beta_prior_person,((logical_lt(n, 0) ? prior_xi : prior_eta ) - get_base1(delta, i, "delta", 1)));
                current_statement_begin__ = 153;
                local_scalar_t__ beta_prior_item(DUMMY_VAR__);
                (void) beta_prior_item;  // dummy to suppress unused var warning
                stan::math::initialize(beta_prior_item, DUMMY_VAR__);
                stan::math::fill(beta_prior_item, DUMMY_VAR__);
                stan::math::assign(beta_prior_item,((logical_lt(n, 0) ? stan::math::promote_scalar<local_scalar_t__>(get_base1(xi, -(n), "xi", 1)) : stan::math::promote_scalar<local_scalar_t__>(get_base1(eta, n, "eta", 1)) ) - (logical_eq(k, K) ? prior_delta_raw : prior_delta )));
                current_statement_begin__ = 155;
                if (as_bool(logical_eq(k, 1))) {
                    current_statement_begin__ = 156;
                    stan::model::assign(y_rep, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                bernoulli_logit_rng(beta, base_rng__), 
                                "assigning variable y_rep");
                    current_statement_begin__ = 157;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                bernoulli_logit_log(get_base1(y, o, "y", 1), beta), 
                                "assigning variable log_lik");
                    current_statement_begin__ = 158;
                    stan::model::assign(log_lik_rep, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                bernoulli_logit_log(get_base1(y_rep, o, "y_rep", 1), beta), 
                                "assigning variable log_lik_rep");
                    current_statement_begin__ = 159;
                    stan::model::assign(log_lik_prior_person, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                bernoulli_logit_log(get_base1(y, o, "y", 1), beta_prior_person), 
                                "assigning variable log_lik_prior_person");
                    current_statement_begin__ = 161;
                    stan::model::assign(log_lik_prior_item, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                bernoulli_logit_log(get_base1(y, o, "y", 1), beta_prior_item), 
                                "assigning variable log_lik_prior_item");
                } else if (as_bool(logical_eq(k, K))) {
                    current_statement_begin__ = 163;
                    stan::model::assign(y_rep, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                pcm_rng(subtract(beta, tau), base_rng__, pstream__), 
                                "assigning variable y_rep");
                    current_statement_begin__ = 164;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                pcm_lpmf(get_base1(y, o, "y", 1), subtract(beta, tau), pstream__), 
                                "assigning variable log_lik");
                    current_statement_begin__ = 165;
                    stan::model::assign(log_lik_rep, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                pcm_lpmf(get_base1(y_rep, o, "y_rep", 1), subtract(beta, tau), pstream__), 
                                "assigning variable log_lik_rep");
                    current_statement_begin__ = 166;
                    stan::model::assign(log_lik_prior_person, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                pcm_lpmf(get_base1(y, o, "y", 1), subtract(beta_prior_person, tau), pstream__), 
                                "assigning variable log_lik_prior_person");
                    current_statement_begin__ = 167;
                    stan::model::assign(log_lik_prior_item, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                pcm_lpmf(get_base1(y, o, "y", 1), subtract(beta_prior_item, prior_tau), pstream__), 
                                "assigning variable log_lik_prior_item");
                } else {
                    current_statement_begin__ = 169;
                    stan::model::assign(y_rep, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                binomial_rng(k, inv_logit(beta), base_rng__), 
                                "assigning variable y_rep");
                    current_statement_begin__ = 170;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                binomial_logit_log(get_base1(y, o, "y", 1), k, beta), 
                                "assigning variable log_lik");
                    current_statement_begin__ = 171;
                    stan::model::assign(log_lik_rep, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                binomial_logit_log(get_base1(y_rep, o, "y_rep", 1), k, beta), 
                                "assigning variable log_lik_rep");
                    current_statement_begin__ = 172;
                    stan::model::assign(log_lik_prior_person, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                binomial_logit_log(get_base1(y, o, "y", 1), k, beta_prior_person), 
                                "assigning variable log_lik_prior_person");
                    current_statement_begin__ = 174;
                    stan::model::assign(log_lik_prior_item, 
                                stan::model::cons_list(stan::model::index_uni(o), stan::model::nil_index_list()), 
                                binomial_logit_log(get_base1(y, o, "y", 1), k, beta_prior_item), 
                                "assigning variable log_lik_prior_item");
                }
                }
            }
            }
            // validate, write generated quantities
            current_statement_begin__ = 126;
            check_greater_or_equal(function__, "sigma", sigma, 0);
            vars__.push_back(sigma);
            current_statement_begin__ = 128;
            size_t testlet_difficulty_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
            for (size_t j_1__ = 0; j_1__ < testlet_difficulty_j_1_max__; ++j_1__) {
                vars__.push_back(testlet_difficulty(j_1__));
            }
            current_statement_begin__ = 129;
            size_t item_difficulty_j_1_max__ = I;
            for (size_t j_1__ = 0; j_1__ < item_difficulty_j_1_max__; ++j_1__) {
                vars__.push_back(item_difficulty(j_1__));
            }
            current_statement_begin__ = 130;
            size_t thresholds_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
            for (size_t j_1__ = 0; j_1__ < thresholds_j_1_max__; ++j_1__) {
                vars__.push_back(thresholds(j_1__));
            }
            current_statement_begin__ = 131;
            size_t group_ability_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
            for (size_t j_1__ = 0; j_1__ < group_ability_j_1_max__; ++j_1__) {
                vars__.push_back(group_ability(j_1__));
            }
            current_statement_begin__ = 132;
            size_t person_ability_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < person_ability_j_1_max__; ++j_1__) {
                vars__.push_back(person_ability(j_1__));
            }
            current_statement_begin__ = 133;
            size_t y_rep_i_0_max__ = O;
            for (size_t i_0__ = 0; i_0__ < y_rep_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "y_rep[i_0__]", y_rep[i_0__], 0);
            }
            size_t y_rep_k_0_max__ = O;
            for (size_t k_0__ = 0; k_0__ < y_rep_k_0_max__; ++k_0__) {
                vars__.push_back(y_rep[k_0__]);
            }
            current_statement_begin__ = 134;
            size_t log_lik_j_1_max__ = O;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
            current_statement_begin__ = 135;
            size_t log_lik_rep_j_1_max__ = O;
            for (size_t j_1__ = 0; j_1__ < log_lik_rep_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik_rep(j_1__));
            }
            current_statement_begin__ = 136;
            size_t log_lik_prior_person_j_1_max__ = O;
            for (size_t j_1__ = 0; j_1__ < log_lik_prior_person_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik_prior_person(j_1__));
            }
            current_statement_begin__ = 137;
            size_t log_lik_prior_item_j_1_max__ = O;
            for (size_t j_1__ = 0; j_1__ < log_lik_prior_item_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik_prior_item(j_1__));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_raschdash";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "nu";
        param_names__.push_back(param_name_stream__.str());
        size_t epsilon_raw_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
        for (size_t j_1__ = 0; j_1__ < epsilon_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "epsilon_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t upsilon_raw_j_1_max__ = I;
        for (size_t j_1__ = 0; j_1__ < upsilon_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "upsilon_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t tau_raw_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
        for (size_t j_1__ = 0; j_1__ < tau_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "tau_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t xi_raw_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
        for (size_t j_1__ = 0; j_1__ < xi_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "xi_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t zeta_raw_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < zeta_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "zeta_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t theta_epsilon_j_1_max__ = (logical_gt(L, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < theta_epsilon_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_epsilon" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_upsilon_raw";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_tau_j_1_max__ = (logical_gt(K, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < theta_tau_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_tau" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t psi_j_1_max__ = (logical_gt(M, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < psi_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "psi" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_upsilon";
            param_names__.push_back(param_name_stream__.str());
            size_t epsilon_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
            for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "epsilon" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t delta_j_1_max__ = I;
            for (size_t j_1__ = 0; j_1__ < delta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "delta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t tau_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
            for (size_t j_1__ = 0; j_1__ < tau_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tau" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t xi_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
            for (size_t j_1__ = 0; j_1__ < xi_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "xi" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t eta_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "eta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        size_t testlet_difficulty_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
        for (size_t j_1__ = 0; j_1__ < testlet_difficulty_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "testlet_difficulty" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t item_difficulty_j_1_max__ = I;
        for (size_t j_1__ = 0; j_1__ < item_difficulty_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "item_difficulty" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t thresholds_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
        for (size_t j_1__ = 0; j_1__ < thresholds_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "thresholds" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t group_ability_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
        for (size_t j_1__ = 0; j_1__ < group_ability_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "group_ability" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t person_ability_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < person_ability_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "person_ability" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t y_rep_k_0_max__ = O;
        for (size_t k_0__ = 0; k_0__ < y_rep_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_rep" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = O;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_rep_j_1_max__ = O;
        for (size_t j_1__ = 0; j_1__ < log_lik_rep_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik_rep" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_prior_person_j_1_max__ = O;
        for (size_t j_1__ = 0; j_1__ < log_lik_prior_person_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik_prior_person" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_prior_item_j_1_max__ = O;
        for (size_t j_1__ = 0; j_1__ < log_lik_prior_item_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik_prior_item" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "nu";
        param_names__.push_back(param_name_stream__.str());
        size_t epsilon_raw_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
        for (size_t j_1__ = 0; j_1__ < epsilon_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "epsilon_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t upsilon_raw_j_1_max__ = I;
        for (size_t j_1__ = 0; j_1__ < upsilon_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "upsilon_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t tau_raw_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
        for (size_t j_1__ = 0; j_1__ < tau_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "tau_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t xi_raw_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
        for (size_t j_1__ = 0; j_1__ < xi_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "xi_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t zeta_raw_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < zeta_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "zeta_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t theta_epsilon_j_1_max__ = (logical_gt(L, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < theta_epsilon_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_epsilon" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_upsilon_raw";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_tau_j_1_max__ = (logical_gt(K, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < theta_tau_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_tau" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t psi_j_1_max__ = (logical_gt(M, 1) ? 1 : 0 );
        for (size_t j_1__ = 0; j_1__ < psi_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "psi" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_upsilon";
            param_names__.push_back(param_name_stream__.str());
            size_t epsilon_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
            for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "epsilon" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t delta_j_1_max__ = I;
            for (size_t j_1__ = 0; j_1__ < delta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "delta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t tau_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
            for (size_t j_1__ = 0; j_1__ < tau_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tau" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t xi_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
            for (size_t j_1__ = 0; j_1__ < xi_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "xi" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t eta_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "eta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        size_t testlet_difficulty_j_1_max__ = (logical_gt(L, 1) ? L : 0 );
        for (size_t j_1__ = 0; j_1__ < testlet_difficulty_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "testlet_difficulty" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t item_difficulty_j_1_max__ = I;
        for (size_t j_1__ = 0; j_1__ < item_difficulty_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "item_difficulty" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t thresholds_j_1_max__ = (logical_gt(K, 1) ? K : 0 );
        for (size_t j_1__ = 0; j_1__ < thresholds_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "thresholds" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t group_ability_j_1_max__ = (logical_gt(M, 1) ? M : 0 );
        for (size_t j_1__ = 0; j_1__ < group_ability_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "group_ability" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t person_ability_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < person_ability_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "person_ability" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t y_rep_k_0_max__ = O;
        for (size_t k_0__ = 0; k_0__ < y_rep_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_rep" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = O;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_rep_j_1_max__ = O;
        for (size_t j_1__ = 0; j_1__ < log_lik_rep_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik_rep" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_prior_person_j_1_max__ = O;
        for (size_t j_1__ = 0; j_1__ < log_lik_prior_person_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik_prior_person" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_prior_item_j_1_max__ = O;
        for (size_t j_1__ = 0; j_1__ < log_lik_prior_item_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik_prior_item" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_raschdash_namespace::model_raschdash stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
